version: "3"

tasks:
  default:
    cmds:
      - task: apply

  apply:
    run: once
    cmds:
      - cd .. && helmfile apply --skip-refresh -l name=cilium
      - cd .. && helmfile apply --skip-refresh -l name=cilium-extras
