jwt_secret: ENC[AES256_GCM,data:5Fs36d6eLQrF8iJoO2qs1iKStWNe/ojlGfbpMZnNW0jcK2Jgj4Qt7AXwnYdduNzP+8Jb+yNXYS5O1gepfutHXQ==,iv:Fi+RuHMWw8GsZIPPOvQWltZ2H0CjNloeAe6LRqWp+xo=,tag:cr05sDUrqFn6eOyUvi3o8w==,type:str]
jwt_refresh_secret: ENC[AES256_GCM,data:uxXor3uKByJc5o8Dmule3Nmc3PdN+Gztk8sZkQh4xIoDU7r5SKDyWoIISLBfZo82Xa1+ZtMGDzt/1L9Laul0pg==,iv:WyDAnCGeLt46iq/j6yrqzZs7HfbgGDPAq9YUsK0N1r8=,tag:NoVfWKo+Y4MGwsMjsHFU1A==,type:str]
creds_key: ENC[AES256_GCM,data:A9UNU5nXbZSns/xs+NZLdhj3rGKL+lZejmVMamF4Ol3H+PgROlj6POuIjBJavv8WIZPyuDljFnpkzONVnt1nBg==,iv:nADpWKR6HqwgZZl038JZfNnmhd1lh9EgqyNODfHO2Sw=,tag:N9BeKhpvI6F8nBbl1dfcVQ==,type:str]
creds_iv: ENC[AES256_GCM,data:D7WoZIuk47ZkWVHYATNWc55ZakcqebiQspPqGGoM4o0=,iv:x891BuFUCscAZviYC0f3qdzQ+xvmC6SX/h4BWivX/YE=,tag:0QZ/nIyxyAB0RmI02esbzg==,type:str]
openid_session_secret: ENC[AES256_GCM,data:Kkjz+3Y9c6XcpkB0mOxxbZmUnBc+z7+4CwLwuysIceiRqAnJfOqpYLDycGdimMCaug47Z9Wxd53rqC0WFBcD/A==,iv:HSYFMJ9uy/xXQhDmI5ypkl03Qi7deIRRvs/zXghMXrg=,tag:SS1kPxyA8HkpcbKKf5rLlQ==,type:str]
meili_master_key: ENC[AES256_GCM,data:LZE+7yUXHKVngmaj0TqacGXSiU5BBxEnOZW5qZ6BqMY=,iv:Loludl98r+ODzgH8V/ptX1xX+o1mIeq+c0OFUSaJS68=,tag:xc3ogbUIJOTJXe1yfrOAxQ==,type:str]
vectordb_postgres_password: ENC[AES256_GCM,data:iw5OFS3jus7nSfhi7pmXcPBgLLaWuC55w2xM/E05MPY=,iv:CPbJn7G4I5lmePMHkDB9yObrqXGgtx5Que0BFR+tURI=,tag:RSCVWwF5rGqW3SplH3eelg==,type:str]
litellm_api_key: ENC[AES256_GCM,data:We8UvkBbKJMIMdFXJALsR/HSsO9sQ+/tig==,iv:RgZ21vaB3LPrwOtjuYNmFCBXGoucQOmywOzGCH5ZkO8=,tag:nAUmL4qO7KwmORrsO4+few==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMkVIa2lDc0pUMlJYNGZp
            N09xcmxvZk13Y1h1Y0hoMkw1cVdrZ29kYlRjCldjSUxGUTZUU3BHUW1nTnJGL3pW
            ZmMvV29pa3piZklzcVo3RGE5NnVpQ2MKLS0tIFNYZ3pPRmJGbXYyNUZQenRvVGd2
            K1JWYkpBd2lWekd4TERMRnp1dWVMMlEKf2K4yeazrBi6+WES/mRKVVUCECHk6fuo
            iDyhZy/WKX2C0GQsbyD3543krwjX6PfRbOMPxPMZGkNMPpIt/76jyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-09-20T15:13:12Z"
    mac: ENC[AES256_GCM,data:fDMmkme9LBfZ8Qvv56lgBZ5ZtJTF6vDYImVu14ExwwCHdcOLeSpnzf8asA6doyF9CcZjJy82UH9bnuFN7sOc/7j3o3tjj4NBB3+tApnhSlVEWCLk6nP5cbQF1TfzYV6K0R7ui7+zoPPiqJKZR+ZaN88tf52+k+dkhOGnYLbnT7A=,iv:WtcKbm8+A/pW6dmkmO2crj0GVbgi+11vaoaulXzlSsw=,tag:V+sePF2Ut5sZcAhBc27hgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
