apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windmill-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 10Gi
