repos:
  - repo: local
    hooks:
      - id: sops-check
        name: Check that every .enc file is not in cleartext
        entry: devbox run --quiet --recompute=false -- task sops-check -- --staged
        language: system
        files: \.enc(\.|$)
