# SOPS policy
creation_rules:
    # k3s Secret
  - path_regex: \.k3ssecret\.enc$
    encrypted_regex: ^(data|stringData)$
    age: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
  # Anything else containing .enc or .enc. whole-file encrypted
  - path_regex: \.enc(\.|$)
    age: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
