version: "3"

includes:
  infra:
    taskfile: 10-infra
    dir: 10-infra
  bootstrap:
    taskfile: 20-bootstrap
    dir: 20-bootstrap
  apps:
    taskfile: 30-applications
    dir: 30-applications

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  stages:
    desc: decrypt, then apply all stages in order
    cmds:
      - task: sops-open
      - task: infra:apply
      - task: bootstrap:apply
      - task: apps:apps

  sops-open:
    desc: decrypt sops files in the worktree in place
    cmds:
      - scripts/sops-open {{.CLI_ARGS}}

  sops-seal:
    desc: encrypt sops files in the worktree in place
    cmds:
      - scripts/sops-seal {{.CLI_ARGS}}

  sops-stage:
    desc: stage encrypted versions of changed sops files
    cmds:
      - scripts/sops-stage

  sops-check:
    cmds:
      - scripts/sops-check {{.CLI_ARGS}}

  sops-toggle:
    desc: toggle sops files between encrypted and decrypted states in place
    cmds:
      - scripts/sops-toggle {{.CLI_ARGS}}
