tandoor_secret_key: ENC[AES256_GCM,data:f3bR+iGd5kCD3YRZAQhBUEaZRhpbtz23IY1cXdLLk1xal7J1sl8A3yj/qnpn99pqQFpHLvHGLOawvu0Qo3/Q9g==,iv:WZz9qbueTtsgaFhboo1cthdvPt0NW2BAtMwjryBC1Jg=,tag:8gKTS6byv+XbN9wM/NEg/Q==,type:str]
tandoor_postgres_password: ENC[AES256_GCM,data:rlWC2m1mKQOeLnQ1NaJ4/62V/KVNe68V8hzUlQnqNeHv9Kvc1bWE8g==,iv:rXK2hJWxHRTgyzUdqcl6mewBFYrpoBLBwP26h2R6uy0=,tag:9AgPRRrfpzfRLbI2eAQXvA==,type:str]
tandoor_fdc_api_key: ENC[AES256_GCM,data:GM0Z5QsYT6evvp+mfCWquyuNFMzbwSuDVOVIVpc8ZYE2I9tcrO1+7Q==,iv:qkQGHyHTMtV/+rCAMQ05WKBahCQKy46jF0/ERyRhJ0w=,tag:W08mcBu7dZxNIVqWNCaiUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHJ3WmpVZ0xmbVFRTmxY
            YUdhSzJOYnczVUJsMHV3Z2w5RU5ZdHE5NXpVCmpnMzVzZmR6cWk2UFVlZ1JFQW5E
            UTZJdnJITGtaU2dnTTQxbnVxUEhFSjQKLS0tIHo4TUJ2UG9mamxMeVJvSERBQ3ZY
            c2dRZUJacFUraGIyUHVGYURBOXNjRE0K5Dxk8LcQztjDGdNC5LzN+5qWP1SZnq4t
            0LlmEC1dgOkKZLWmxcwC62npJNy4MjML/xxVzbVw3k1tRfjhjK/AWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-10-05T17:33:56Z"
    mac: ENC[AES256_GCM,data:GWSd7HvXapCnKVxHRDwnD6jR5IWj1VdKtEpT5ikZX8MwWNnsCHi9VgDjIF0DdUN2o6ByZ0RiXLVdazdbjUY2eGNRQ26aE+wd2V4RWFwb1yx66dMIf41Ljn7VBgZLOSF2Ixh17buTHcQqoOnGbFc6ZzEp7YV4L/5UTqzQ4G11guw=,iv:PSR3BmqsQ3KMYDckwb3wWJiyREcMXYiHAI0tfPIv8Ig=,tag:DmPUKRSwzIo7CrkLSRwfhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
