apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  annotations:
    helm.sh/resource-policy: keep
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 50Gi
