apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-db-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 5Gi
