"all":
  "children":
    "k8s":
      "hosts":
        "k8snode1":
          "ansible_host": "10.10.10.220"
          "ansible_ssh_private_key_file": "/home/cerfe/Ongoing/HomelabSetup/rewrite/opentofu/keys/nodes"
          "ansible_user": "cerfe"
    "tailscale":
      "hosts":
        "tailscale":
          "ansible_host": "10.10.10.221"
          "ansible_ssh_private_key_file": "/home/cerfe/Ongoing/HomelabSetup/rewrite/opentofu/keys/nodes"
          "ansible_user": "cerfe"
  "vars": {}
