chhoto_password: ENC[AES256_GCM,data:HBinKsZSoT8Lbspth087xJ5DNAFMPR9HspnHwQ==,iv:1m4AExbBG0f9b6MQsMWia159BQMg03Lfyl0vbHLDYUY=,tag:494JDIjHWF3BwHR2zmPnGQ==,type:str]
chhoto_api_key: ENC[AES256_GCM,data:Vdh8SeUwQ9FVZgZLmgsqHXDD1Kk5qrH76Bgt/zIjc8dMs2EZLg6Hjtz1OpdKMzQr,iv:jXr9wBbHYjZCXIss3nHkKx0wLl7qlEFkeUpLZee2cjM=,tag:opBeuvqxTYnSoRgG4HxOFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YUx3aWJJQWF3R1pnU2xH
            ZzVHR09LS1BDNGJqQ3BVdGd5dFIyWnl4ejEwCkY5SnRBN1FQNnZ6RXJBTlRENmFo
            NVZKM1dRRml3UVY4dERIMi95b3RjcTQKLS0tIHVkQ3VwYmJWU2VWUW9MT3FzckJX
            VWxoLzBmZjExU2pmdjRYc2Vjd1RlRUkKHCpAJRQKiouOGi0UsIRmXEv2GTHboVuJ
            g7MngPaECxqRWmBUemCvGpoqa9PNKJwg6dxb25CwvMpVevbfukmFNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T09:53:50Z"
    mac: ENC[AES256_GCM,data:rn6i+6lYDgUkGbyp5MDhIRzzXd//jyyJ/y3vgekMEln7y36ZRvr4yNbSnOuHWwLyU/pF1hUT9ftQErP/5WcAFHClSWuGjSpsq+CWfj2L2FsyTXU1UMT2UUsXyS6a5zpvwmIHZ0eaHgJLXmb50MxKDMuYe0clScizPmSNH7G9CnU=,iv:+5OIOymUYyNbD3scTXboR9L0GKnm193jddblxLHXak0=,tag:34HsRW7Ndfk8YG5jE1aAYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
