chhoto_password: ENC[AES256_GCM,data:E29XtHt/OVxlf6hbWtXGVEudr0v7Cq0XM5+ndA==,iv:i1wV5WIslk/bGKQ4kC0Q4YOc38F57Dvtr+yTyKgiFPY=,tag:249DtlOIbwbVS4l/v0CX1g==,type:str]
chhoto_api_key: ENC[AES256_GCM,data:OU1ps38yEWserXwYAVhCgMurxIsGVt0pESlxcxnfo6Dyb5IFnpGQgX0hzYKjPCJV,iv:rFxfyONljzL6Iw7dGiI8J6SUi9uKqK1s6VXFenEmiPA=,tag:XW8RzFYvsJwznqVDSkqP6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTjVFVGx4TDN3L3RYK2Zs
            Z0J1WGFUSC9MeXQvL2NnWm84aUNSYXJmdm40ClZpdGNXd1RCOXBXN1FsY0tlUVl0
            cHgwRGc1dTVpcnpjcUdIYXZKd1EySlUKLS0tIDU5ZTBhVWFhOWJqOVRRNlJhU1NT
            azJoMWQrbDFIU3JZVW9QRklPMWxSU3cKI0V6Vh7f57voFtlrpOFZXZsvkdRaBeLR
            PaxaaiZx42ltIe8F5VT7Vr9xhCiIeuPR5GS8wITh2X8rM+SHouxIyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T09:52:50Z"
    mac: ENC[AES256_GCM,data:0Ln0LQItJxmMB2Dk612GJjdssVhttYXpsb4fzzszp76OtS/qUrCUEGZZ+sAc4mS91BtpjeaE/wj+dN6iA0L8d/XEuSoPEeBwRpyLKBEttBIPwDEVVsQEl7LKRZ8lGP3w2zys+2cC97jge6pDUPI3K/BbTImfCB7hnwfJeqiP9k4=,iv:flwxCga2Mr549lJs65lpQWCuN2sdb0Q/5xFkjhL3XJU=,tag:evTmLc8T7a/IpwjSPh2GGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
