environments:
  default:
    values:
      - ../10-infra/generated/generated.infra.yaml
      - app-registry/generated/generated.apps-summary.yaml
      - app-registry/generated/generated.oidc.yaml
      - smtp.enc.yaml
---
repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bedag
    url: https://bedag.github.io/helm-charts
  - name: authentik
    url: https://charts.goauthentik.io
  - name: immich
    url: https://immich-app.github.io/immich-charts
  - name: nextcloud
    url: https://nextcloud.github.io/helm/
  - name: k8up-io
    url: https://k8up-io.github.io/k8up
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm

releases:
  - name: csi-proxmox
    namespace: csi-proxmox
    createNamespace: true
    chart: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: "~0.5"
    wait: true
    values:
      - csi-proxmox/values.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: "~1.21"
    wait: true
    values:
      - cert-manager/values.yaml.gotmpl

  - name: cert-manager-issuers
    namespace: cert-manager
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - cert-manager-issuers/values.yaml.gotmpl

  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: "~41.1"
    wait: true
    disableValidation: true
    values:
      - traefik/values.yaml.gotmpl

  - name: kuma
    namespace: kuma
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - kuma/values.yaml.gotmpl

    # BACKUPS
  - name: k8up-globals
    namespace: k8up
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - k8up/extras.yaml.gotmpl

  - name: k8up
    namespace: k8up
    createNamespace: true
    chart: k8up-io/k8up
    version: "~4.10"
    wait: true
    values:
      - k8up/values.yaml

  - name: backrest
    namespace: backrest
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - backrest/values.yaml.gotmpl

  ####

  - name: pihole
    namespace: pihole
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - pihole/values.yaml.gotmpl

  - name: authentik
    namespace: authentik
    createNamespace: true
    chart: authentik/authentik
    version: "~2026.5"
    wait: true
    values:
      - authentik/values.yaml.gotmpl
      - authentik/values.enc.yaml

  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - cloudflare-tunnel/values.yaml.gotmpl

  - name: immich-extras
    namespace: immich
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: false
    values:
      - immich/extras.yaml.gotmpl

  - name: immich
    namespace: immich
    createNamespace: true
    chart: immich/immich
    version: "~0.12"
    wait: true
    values:
      - immich/values.yaml.gotmpl

  - name: vaultwarden
    namespace: vaultwarden
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - vaultwarden/values.yaml.gotmpl

  - name: psitransfer
    namespace: psitransfer
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - psitransfer/values.yaml.gotmpl

  - name: paperless
    namespace: paperless
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - paperless/values.yaml.gotmpl

  - name: syncthing
    namespace: syncthing
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - syncthing/values.yaml.gotmpl

  - name: woodpecker
    namespace: woodpecker
    createNamespace: true
    chart: oci://ghcr.io/woodpecker-ci/helm/woodpecker
    version: "~3.7"
    wait: true
    values:
      - woodpecker/values.yaml.gotmpl

  - name: nextcloud
    namespace: nextcloud
    createNamespace: true
    chart: nextcloud/nextcloud
    version: "~9.2"
    wait: true
    timeout: 600
    values:
      - nextcloud/values.yaml.gotmpl

    # *arr MEDIA STACK
  - name: media-extras
    namespace: media
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: false
    values:
      - media/values.yaml.gotmpl

  - name: jellyfin
    namespace: media
    createNamespace: true
    chart: jellyfin/jellyfin
    version: "~3.2"
    wait: true
    values:
      - media/values-jellyfin.yaml

  - name: seerr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/seerr-team/seerr/seerr-chart
    version: "~3.9"
    wait: true
    values:
      - media/values-seerr.yaml

  - name: sonarr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-sonarr.yaml

  - name: radarr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-radarr.yaml

  - name: prowlarr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-prowlarr.yaml

  - name: flaresolverr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-flaresolverr.yaml

  - name: qbittorrent
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-qbittorrent.yaml

  - name: bazarr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-bazarr.yaml

  - name: unpackerr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-unpackerr.yaml

  - name: grimmory-db
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-grimmory-db.yaml

  - name: grimmory
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: true
    values:
      - media/values-grimmory.yaml

  - name: autobrr
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: false
    values:
      - media/values-autobrr.yaml

  - name: managerscript
    namespace: media
    createNamespace: true
    chart: oci://ghcr.io/bjw-s-labs/helm/app-template
    version: "~4.6"
    wait: false
    values:
      - media/values-managerscript.yaml
  ###
