environments:
  default:
    values:
      - ../10-infra/generated/generated.infra.yaml
      - app-registry/generated/generated.apps-summary.yaml
---
repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bedag
    url: https://bedag.github.io/helm-charts
  - name: authentik
    url: https://charts.goauthentik.io

releases:
  - name: csi-proxmox
    namespace: csi-proxmox
    createNamespace: true
    chart: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: "~0.5"
    wait: true
    values:
      - csi-proxmox/values.yaml.gotmpl

  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: "~1.20"
    wait: true
    values:
      - cert-manager/values.yaml.gotmpl
      - cert-manager/extras/extras.yaml.gotmpl

  - name: cert-manager-issuers
    namespace: cert-manager
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - cert-manager-issuers/extras/extras.yaml.gotmpl

  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik
    version: "~41.0"
    wait: true
    disableValidation: true
    values:
      - traefik/values.yaml.gotmpl
      - traefik/extras/extras.yaml.gotmpl

  - name: authentik
    namespace: authentik
    createNamespace: true
    chart: authentik/authentik
    version: "~2026.5"
    wait: true
    values:
      - authentik/values.yaml
      - authentik/values.enc.yaml
      - authentik/extras/extras.yaml.gotmpl

  - name: cloudflare-tunnel
    namespace: cloudflare-tunnel
    createNamespace: true
    chart: bedag/raw
    version: "~2.0"
    wait: true
    values:
      - cloudflare-tunnel/extras/extras.yaml.gotmpl
