version: "3"

output: prefixed

includes:
  ai:
    taskfile: Applications/ai
    dir: Applications/ai
  app-registry:
    taskfile: app-registry
    dir: app-registry
  csi-proxmox:
    taskfile: csi-proxmox
    dir: csi-proxmox
  local-path-provisioner:
    taskfile: local-path-provisioner
    dir: local-path-provisioner
  cert-manager:
    taskfile: cert-manager
    dir: cert-manager
  traefik:
    taskfile: traefik
    dir: traefik
  k8up:
    taskfile: k8up
    dir: k8up
  authentik:
    taskfile: authentik
    dir: authentik
  pihole:
    taskfile: pihole
    dir: pihole
  backrest:
    taskfile: backrest
    dir: backrest
  cilium:
    taskfile: cilium
    dir: cilium
  cloudflare-tunnel:
    taskfile: cloudflare-tunnel
    dir: cloudflare-tunnel
  immich:
    taskfile: Applications/immich
    dir: Applications/immich
  kuma:
    taskfile: kuma
    dir: kuma
  librechat:
    taskfile: Applications/ai/librechat
    dir: Applications/ai/librechat
  media:
    taskfile: Applications/media
    dir: Applications/media
  nextcloud:
    taskfile: Applications/nextcloud
    dir: Applications/nextcloud
  paperless:
    taskfile: Applications/paperless
    dir: Applications/paperless
  psitransfer:
    taskfile: Applications/psitransfer
    dir: Applications/psitransfer
  shortener:
    taskfile: Applications/shortener
    dir: Applications/shortener
  sparkyfitness:
    taskfile: Applications/sparkyfitness
    dir: Applications/sparkyfitness
  syncthing:
    taskfile: Applications/syncthing
    dir: Applications/syncthing
  tandoor:
    taskfile: Applications/tandoor
    dir: Applications/tandoor
  vaultwarden:
    taskfile: Applications/vaultwarden
    dir: Applications/vaultwarden
  windmill:
    taskfile: Applications/windmill
    dir: Applications/windmill
  woodpecker:
    taskfile: Applications/woodpecker
    dir: Applications/woodpecker

tasks:
  apps:
    desc: apply every app
    deps:
      - ai:apply
      - cilium:apply
      - csi-proxmox:apply
      - local-path-provisioner:apply
      - cert-manager:apply
      - traefik:apply
      - k8up:apply
      - authentik:apply
      - pihole:apply
      - backrest:apply
      - cloudflare-tunnel:apply
      - immich:apply
      - kuma:apply
      - librechat:apply
      - media:apply
      - nextcloud:apply
      - paperless:apply
      - psitransfer:apply
      - shortener:apply
      - sparkyfitness:apply
      - syncthing:apply
      - tandoor:apply
      - vaultwarden:apply
      - windmill:apply
      - woodpecker:apply

  setup-helmfile-repos:
    run: once
    cmds:
      - helmfile repos
