tailscale_key: ENC[AES256_GCM,data:+YWupqmDJ8IawfUNbSNmP4vq0Q0EeR8SKAmfJpcOnp+AIp8TaJUqBiWm3C1TbF9CRGZ3nmQAi4ibG0dejQo=,iv:HlvDrn3b8vgrOaw2nYIl5IBuMq2eyISbdadxBJTFwAw=,tag:6nEF6zJLulB+9kJVN1CEEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbU42TUVLYmRXUU5ITHA5
            TlNtQTBhbDZzRUQ4elZGS1hxZHRKTlRNdjE0CndCUGdBd1pwYmR5NFVWeHN4RGJi
            Q2VMSjJBN3U4cUFXZUZoTFllRng3Qk0KLS0tIFlPYW1SOTdqYTdPQUYxS0pQVlZW
            YXlhQ1AwQ0dOME1VMSswMjlNcEh3YzgKdDrbCbwq7546/uvQqkRLP/oszojETyFO
            +7j5nK0lyYpmIJMVnSkZfLT0+fxLNPWgUrv2xpF0vCi5Aq5nORXMXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-04T15:43:23Z"
    mac: ENC[AES256_GCM,data:p4ushhkvy7B40ybEidw4xlaUw9yDn4zMyN07pwOg2u5o07GXgb95Kw2ssupUueLfqn0WFzLX6Wx+hTngUwhQR5DErnmzOdQvfAJJ8Olx385bs6N67wDxlVGbzE2bPjLUfDVAUT7kdiZgR8mTGENf+pB9s2dGa2UoBEvT37ikJeM=,iv:giBmgj1smyHjzutAE9PlseUW/scDU5clgSsfZOpkWEI=,tag:KPYeqU7K49kbiIAM5XHG0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
