tailscale_key: ENC[AES256_GCM,data:nvOwSMfNkb0AfXPusjvHggC9IwnxCRTvfNyC8d2c4xbzspiAD95Z9I3ypCdKpa+hSW/dsKSlEPeAB9rhQ0k=,iv:CG0dfhwDRKRFPD2YLL5J2iNojlZBH0tzeQutGRvRXhc=,tag:uP1SIzHCZAFZKhXPkHscTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZk5aUVBBaGNXZWhhaDEw
            QkVxQUF5TXY4SHE0UmRvWXRYWWtnYnRUK2dJCnVtUkpaSi9zUEIxWEdHQ0xNcmdo
            RGZCOWh4OHgwYzBCVU9ENzVib2sxNmsKLS0tIEl6WHBFL3dtU2h6bnNjU2dvT1M5
            ODlOWXArQ2VJS2hsc083a2lUUlF2UTAKCQxH8AzRZBXdqtiXfhR//udeL2TmtuBs
            dhW92mGDZydrDr94VQoYBiBQQ2HiMudT6TKjoefBqkCLSa7D1xZw2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-05T12:49:57Z"
    mac: ENC[AES256_GCM,data:rzaekpgEodDGDHJUQ0B1e2yE87SfJw+TWKxubuu+hOviKFIkfBJPwNgYM/onSDO7X5g1c0T/bQyikiaIp7nnFD1NxmwdK7zN66gruyZJaBuSzOLjE97j3Rw2y6ICGNzROrvdh1mhQvPb05dIEms+MDcni9istFcJv/EYgtVnG+I=,iv:8NlFOWCsJHkbMu6IaiDv41Wu9tWsDHGbb5s7gS6njDw=,tag:iM4DGqHqRXp/28nlyPGZKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
