apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psitransfer-data
  annotations:
    # transfers expire by design
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 50Gi
