psitransfer_admin_pass: ENC[AES256_GCM,data:7prYQFe3X0cQWz4Uf+5hB007Q0U7qwPcXA3F3w==,iv:q4cdkOyIlZSlOyn2QBuwCdJ+iFQhfdxLTOvldtn/LMI=,tag:8vsI9M7VgLP5LhnnbG0qPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbldDNEtDeFFRY0RDU0tH
            VFQwM2RNeFpBMVhtZXpDOTFVNGg1Z29ZSlFJCnE1UGg2a0pYQ2RyM210bFV6NHRB
            ektadnlJRWhXZXRudTNtRkVSOXZtMTgKLS0tIDRKWDVWVmVVWm5ybzBlalBXVXNC
            UzY1OVZZTUljUm5HZytnYVlIdWVISW8KG37VfME8A1UE2fCfKSBy/HCJ5fIs5LFM
            dJ3UZm1BkwZDA7vfuBt0JUFdGgU47LrNUscGy+f10SS4H87XOD+kug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T09:53:50Z"
    mac: ENC[AES256_GCM,data:CuQy96bTpBmfjsJxP7PhTCzgcFWfrAUqHBz/RoCCBCOxiYS0OLCI0B7gBBhdz5iL4+J5Y5xjQvkDkfUUxkXjpD5v9xy6qU4ot7YBp91CC7fMEsIe+xGe3r7RpGgKzIYKE+CTihknoiU0MEPL3HzEvZGbWwB18srevsYpYrS65Zg=,iv:MW9AaVBvjuHb9hMagLktCAxF1YxNRPgdbUDEUMt4hWw=,tag:uzd0dmBE8DpKds0S886KzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
