psitransfer_admin_pass: ENC[AES256_GCM,data:peUWdtxQO758+9/fCUws/SliIltajUWK8lVeEQ==,iv:czE9A9pVbc3BijVzry39xAAuWDvoxv3VDz30NLTd9GY=,tag:piUscQm8G+k1OnSluVN2TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN09yWTRPeVE4Tis1MHJY
            YzBJSnphR05zSVRkSXc3Qi90M2oySkF0K2xnCk8ydUNvbXo1eW5FeTJ1SFBodEov
            V3V6aERWajVpazVldmppQkJ5aFQwc00KLS0tIGthUmlvUjc4ODAvUUpwNjRHUUty
            VER5QXYxbTg4K09Kbllub1VHWVdmbW8KOTGgNuM7Cg4MPPw27y1lQaYV0atw4DJA
            AVyqOpAHOoNef3T7ubpq2Q+JnumLiYo1D+CsOFN0jDolVLG6QNTYDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T08:32:34Z"
    mac: ENC[AES256_GCM,data:ND7KqB2OoNBU/+59e51opTx0eXokkSonK30TP6n0VEIsBFXRZ2jMYl2vDESvjsEX9DqCMFdonbT6gbSUekyMaG/k6pZ3hFBq5KHKP6Smv8b94TJTR3z4x0tqh7nqnfs6Y9EFkwL03aIwVy0vuMR9lQ1yYGXSSDYjskYL3oX9hdE=,iv:ESuUbpG/5MvmXoOKLOyORFwaX6GWdanU4DIGoCDye6M=,tag:zfPM5SCXosCFsgAh2dytzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
