#ENC[AES256_GCM,data:HahSRQ9BVm7QHvqLf3/ekgkf7YGvVAjWmoESQORAV8vQuG2u0cJXBW6L3JfZiWQbyRkDuUTyP1BK3r9OGyDsDEY8CalEM1VCGlTT,iv:MEI1WNZzHTdMKc+c06q2aPsOIUmiVCDOT63xN8EVvco=,tag:8hXp1YwJxt3GotIDgoSx0Q==,type:comment]
#ENC[AES256_GCM,data:h4iKmrL3hxl63p2o6Q35fwdUH+MuVSUqIgVZOyF3zbQB,iv:DfjbAUh4XC8KOGhGBmqErZAlX7NUpU2wmuJcpm2lTkw=,tag:2oWYk65IEcc/g1PutWzR5w==,type:comment]
#ENC[AES256_GCM,data:yB9VjXOdcSP6Br8oeYZyRyZiyg8KBF8f0SM=,iv:RP5LFCQkvhU580R4jC/JxcIZ8Y/TBfdiP0rWTii7zIA=,tag:EOWSSj8A71WlAgfvBZzJ3w==,type:comment]
#ENC[AES256_GCM,data:fG/e020pJJGAnnzZvbS6sg==,iv:VOhW0SgpFehzQ3cAtXOzpinBPHCitYHb+ShSeuQTzKI=,tag:G9Lj/w5OmCLpP8JErmgCAw==,type:comment]
token: ENC[AES256_GCM,data:EUU1X3u1RUNUVT0IRHejP7+9ldRIez/rgkLjHmvMrFyXnstLWGMpJrPHSIQV9B26xDraCF8c9HktlSWPrDa2p5htiWt5OQnJlIOjkty/jDwr4HEvVpmHAw==,iv:e/vMXze0xf/gCSeF4itOKlxMgX5hQUdMg2LSJ8T8hHc=,tag:SGmXLytI+kiljjx99phs/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WDVkRDlqOUhrcG04R3hU
            V0YxM2hXNDdXUXZiMGFwc1B6UzhLSmlTR1JjCnZMMFF5YUM5K1dVVkVCRCtSUHhT
            aVp5eWdvYlYyUXlKa0d4Wm5LSlhEK2MKLS0tIEYxb3JjUVorcTZ2TDRDR2UyWHRB
            TkVEYVVIcGFFSmtyeStUT1FBM0NFSVkKv3YD5F18qtGgyTTGI/IuT9+Z7LzBv+s0
            A1kkdB7KDqDLVzyApN8yiyuPZ9Rs7dDGmoPEfnK9zFiWolZjVeWgdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-06T16:19:17Z"
    mac: ENC[AES256_GCM,data:jImxp/qALVZ5JFKChDGdnodK7nnBxjXrZToSrDVQw7Ldl56K2t11RoEzVt60HFxIZ9jEJZgAaf83IAPsOkiatXP/CIlM523p2P9a2BmGuDIOLmzi8Fp73vazO5QWjHV5StzKh6uNx5kgCGLzPvrISxj068UAyAtHRd5Ux+m9SGg=,iv:fusSEUccglh1Zblb8YAsKl2p8x5MoQS8NVbyhiZu3kc=,tag:mnug9ug+HU3kSqJinwN9eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
