#ENC[AES256_GCM,data:olwL/4fpJs4ioLFp5+D0r2tPoRfJDPerGMgGqktKdmJ16muFCb4gwjdYkEcGYm73VWd/uc5u2en7Dlm9F3pN1TwfbIN/gc8ghRxe,iv:4yigTt6Y6zuMrHJAVuDHzGyl49+PNOlo4ZMt9F6163M=,tag:CXQFxAKBlVVdvXzzTQOmWA==,type:comment]
#ENC[AES256_GCM,data:2TrLBPuQb3KEEvQLNfEbR/saL69Ur2ISyaRwQogTo24H,iv:wiNKvzJVsVB0PpCrI4ZQMWIOeMKqHjptScZnI5fvtTo=,tag:5lqTT2KUh8pMxJrTwZvq6Q==,type:comment]
#ENC[AES256_GCM,data:0s/DCP75LMZ8qroTanz1BO2+zebyNBMrK64=,iv:hijcmhstT0TQr/lrbNo9DDInaXKAB900VQZExP3U8mM=,tag:XDfejuUtfrqsQ61JOcv2qQ==,type:comment]
#ENC[AES256_GCM,data:pjAXJpa7m6q3UwwtaQWRdA==,iv:6ZMff4mXewp+MhyYGXSc1ndZktacDIBqx6b0mA8zmMA=,tag:8S/Euh+r2pRjCAdQ9q6ZRQ==,type:comment]
token: ENC[AES256_GCM,data:oU3Y95Il2HzLSELI6pmAgC0Z392+ms2QvsXS5GZV3UKippNHlV0/VHyX5lB80OWWpvCI7xg2OPdwWlFk+Ogm0d9H5u73uCF/kWJzbQpkxM0+P7ysKndzLQ==,iv:PmtE/cBs6Jm1syI8B2CBU6LZ1hkKbt6+krJmROe4MqE=,tag:v6QLJGJNrVbm3gsVa+SZpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMk16d25XZ0Q1WHEvUUE1
            Nm51RG91clNIOHNFcTdoQklEL1RZZDFpWkZRClJhaGN2alVTWGJmZ2J3cjdEbDJX
            THFFb3RHa280bjFGN1hBbnFQMWs1M3cKLS0tIHJlMy9lOXY5NE83aXhCTHpjeE85
            TzRzT0YyU3czVzNQSjVPeG16T0xLTEUKtCvIvTXlPnIeGs+jGTbYTgPmJr3VUEWU
            9R0eqWJmDkGuQJxJ//C6wgR0Z9nF2mmZvB1PdDswgyYyByPTsb3RJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-04T15:43:03Z"
    mac: ENC[AES256_GCM,data:Xyiz/yRmnVsViHivFGtzu0ofepzQJi1bcg/LYcCV8dzX5ZqiEWKR1ht9+y5OmtC1AFWJ214X74JMbXcx+H8zHeESO4Xg2D9CIaZRSXSxUTDzIHWXc/DIgSZjaqfmXV9V0TDC8Hml4MeavrF+lSmfvXsTkuD/OkEAc9X2Z1IBMFw=,iv:5FZ8dd6RIkZgVJE/rrbyBrZ1+NgYtWjK7AjKY1x/J6c=,tag:24hJ4D1qqlvSRLr0MMri8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
