#ENC[AES256_GCM,data:nnpU8xfcTkuasSp65gY+2aumiMKIdVjHaKo9okkQCaFAmtMTuna1dRn0NSxi1Ze+WJ3KIJRRW3B3CkO6MsVU6duQem50jnUeOSwV,iv:+Gwnml472z+T81uDnYVDZ1gJkTDSK4PT79ZOnsCO8bU=,tag:CRtMOS5mBiITBoSioJVEIg==,type:comment]
#ENC[AES256_GCM,data:6QW379Rx9B3qzR85cFV7uksSLc6M6Gla5JffCO3TrxtQ,iv:8JBrTvR0VpPIW2YNoFILFen1kD4y5ouFSqyjJ4jJf3I=,tag:k3hyp534Aqsn/EuEXAKpMg==,type:comment]
#ENC[AES256_GCM,data:SnZ+2QDp89vLvLLhyLVr517HSBQrOh+X6h8=,iv:ZrQDggikMjhYlwKketxgUub3zUMs1RYYuPKh2ZBxWpE=,tag:oIL3j8whF0DOFRMYVKQrnw==,type:comment]
#ENC[AES256_GCM,data:8t2eM4tj+PTcx67AXwLedQ==,iv:qtVGO/3BdxvUAbbLIiGKwxKJZAL7UVJ8q2R/yd4Ch3M=,tag:4chQvshF3Rta1kNnGj79RQ==,type:comment]
token: ENC[AES256_GCM,data:18JM2c9dLwgvVjsT2/31tkxzL25LeWMkhBo0Rjxk11kGtnhTA4G5sm7CCaNcx/dAItKiemPP2mtNMBkz99JNxTd5KKD0VuKw+AjlH7spFUg1emTByYiN1g==,iv:ITI1F8fsqaKGLW4YufQQ3ndKsZNkhvnR5Sq6MlgNa8o=,tag:EkzT4Kk463MwpIMQzRiSJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RitzZXJJSEc3ZE4wV09y
            a1ZKd1A3M0xUc0pxVmR6U0ZOS09YcnNJakV3CjJhbGhCY25uN1Fra0hpdFVUOEVs
            VUpmbTNOT2Z5TzFhTzlFelNDQjNKTEUKLS0tIDFLSEpWKzJ1WjVPaUFtdnhoMlRI
            dmIxckUzVmRHbjhRMGtuazVLUE9acWMKLlF+owkFpz7fwx3MeCJzfhKmod+kv77k
            ydQ/UreQna+2bPoEZWnXumWjg85pJc6J4XiEUBM8SgcObrGFc1bG+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-05T12:48:00Z"
    mac: ENC[AES256_GCM,data:xTLuJzBNhbdgV59SStb5j07xvbB3YSvf0JruNyWEJpxQ9ALhhdC/1HOelTnBCZwQcQ6ZP6qTHNulBDMRYz/asZ/kBIo1sI7YC/1QFqwvC62BseRVIFqUSjpTRJLlZcdV8dbfHf3J0zFpvWGsIxT7twnLWuc5OsBVkAOBS/tMjyE=,iv:DmB5Ip6lqesPZ2r4XDoqaK+g7RZICkt/qvLaXlV6aTo=,tag:SpjZFtJyOi8THmkYcAYhOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
