#ENC[AES256_GCM,data:7i76Wj2OhILVin7lD4I20H+Y8TdqWp/KNyD+0/sGkqkfgg/Rzb7dTSYZF5N4OuUPVI2XVcElsL939bw0xAk0ssvKD040DLBQk8ur,iv:0c8EWfIApBxxnbEOFDTLkGYzej/c6g815MoAD4lDI2Y=,tag:D5luUbifyfG0SzOod3EsOQ==,type:comment]
#ENC[AES256_GCM,data:bbJmgTg6jaRxywq+OzYYJx52QLzFspYf3fB9NLGwm8EQ,iv:llRsRqYfjfpfAaufWC+/UJecn7I5+Ip9wc3ZkB9/Mqo=,tag:946+sfwRkCLXtjxSpSLlmg==,type:comment]
#ENC[AES256_GCM,data:jYa0SeZ6BxogI2YdSzt/VqeLurbz7zudTjU=,iv:oD7A+/up2jVZg0YqwFYzL6orZfigvJ9LKc/SofqpcZE=,tag:n3jxH4wEbRvvaxmm9JhEug==,type:comment]
#ENC[AES256_GCM,data:c8zS1XfKxXfaWywv750nAg==,iv:DNmRKCQmrWpHe7QuuMob9EYt3SSuBgwiI0bsQLPSljA=,tag:auQHY7ONZyrVUpoPICEdYg==,type:comment]
token: ENC[AES256_GCM,data:H1luCkTuN6nQXvwJaIlqWjy4x0lqxiTgcYytdi/BTB6pdDpG9A9SbtlZzD1MaGKR+VzgIu2tL135AY3FkJAgK7LsRrnoFnoiiH3W+CMyMoY7u5XJh6b9cw==,iv:kbwHe4u7xrts0E3rgCcEfaKYIbJYJCOHhVTLkFUvYQg=,tag:6zpUZLdwgcKlJhcWQ0j0qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybjkreUkxbFd0S0NMbkxm
            TFQrQVBrQzFuSGJ6OW50SW80TlFFb01jWW5FCkd3UUVJaklDaTVFdEtkVUJnZDdT
            c01Ka08xNnhlL00rbWR3QnRqNWVtSUUKLS0tIEVhdTNGQXpDNHJUT3Zub0JCbkdX
            cTdhTEdBSjllM0t1S2VPTW1nU044Z0EKGl5FtGKU906pWOhaHwp94kLG+WrwLZbI
            PAiRq1NJT6y+khCWvzIHPkGuXsz1N34Wl83C9JIvPmfnmYyyqX7Xag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-07-05T17:12:08Z"
    mac: ENC[AES256_GCM,data:UWvLrU/9nbqyQw8Em5DIu6eC0+S1XDBwzGruo+2coeJsbHWnBAZzqYsJW/TtiBVkzmPkoyDSImWZnmnuPCF+sGyw6dCHXpqH3tkId6I3hVL1lghduaB/UYwLge8XZjg41YS44bjeu90xrdrX3+e28b5vBhd/AxIcE4ND7I+Z3WU=,iv:uIMtcTb8jrYJ4iq9f++eEaLIMej3r/09ATuzy/bK2hA=,tag:hOPE/8CTwvTN+Z1fUnazFA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
