apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 2Gi
