version: "3"

tasks:
  default:
    cmds:
      - task: apply

  apply:
    run: once
    deps: [':csi-proxmox:apply', ':cert-manager:apply']
    cmds:
      - cd .. && helmfile apply --skip-refresh -l name=traefik
