apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 20Gi
