#!/bin/bash
set -euo pipefail

tofu apply

header="# GENERATED BY OPENTOFU (generate_ansible_data.sh) — DO NOT EDIT"

{ echo "$header"; tofu output -show-sensitive -raw ansible_yaml_inventory; } > ../ansible/inventory.yaml
