apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 8Gi
