apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    # the pod's backupcommand dump covers it
    k8up.io/backup: "false"
  name: nextcloud-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 10Gi
