apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-clamav-db
  annotations:
    # signature database, redownloadable
    k8up.io/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 2Gi
