windmill_postgres_password: ENC[AES256_GCM,data:EI9zjz0JYMfdoDHzMcyP8ftqrux072qPBRIHAQ==,iv:A7/V59SaTo3RMg6F7BzXZ1sMD/hhlHTyEzX857fhq8Y=,tag:GU0ld+7BqO5XqFvj/+5dmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNmZCNWVHRFYrekhhYmI3
            L203UE9SS3lJNFRtYUxwb1JHWTNJMkpmWmpJCjVianJsZHIyaEN2NlptbGJpUE9P
            YnBrbGxWVEo1M1dtaGlic2xhSzNjODQKLS0tIFdVQWF2NXNmN09hU1NTYnQ2OXUz
            SmQwempzTXlMcE9na1I4ZHpUaU1aZHMKv1gTzE1FavoJ0mcvS3qIMk3yTu15bKtV
            Z+Uzr/64LfkHQXfJLvJoo6wtF9H5sf70xXtFWqdz/FPiuLy1baqhQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T09:53:50Z"
    mac: ENC[AES256_GCM,data:c+9paz1zbXue+gS/YxCmg7s9lIv5Kuo5sjWF8XBC1P1GWbvvFcaG3G2jSLom+lJ0Q0eriECcIx8ystinvyeqoYPgAz0nFGKBqIigamjw+mGXfShwc31tDG161B5+ROobkj165wyxEk1W+5LYqKKBmzyIYl7hMnm2Ll3S0slu8UE=,iv:d4sF7CCe93CO08hFdeHyXruVZDiguVZg5gkD4XgDSYM=,tag:1KuhxyYdfk3LdtxxSwrmfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
