windmill_postgres_password: ENC[AES256_GCM,data:zVkJVWYg8dRpLlu7nllG/Qn4cBV5sX+f8vJ3VA==,iv:Yo6UflpPn0l4d/9wvqtbQEwPV8wtYK39rh5ZYmgr5vc=,tag:NZIF/hHPhJi2myOvvQjWag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQmoyQ04xbGNUTytIUysz
            Rm8xMTc3Zk9Tb0x2TlBMRmdhbmdkTXFzQzBZCndReDhvRWhETjRwNVVoSU5YL2V1
            QkpsQVpVS2pzVUcwRnZLaW1xWk9OMDAKLS0tIC9sYjVkUkRtR1NCN1lDRjMzM0t4
            SXNmdFJoUTlNZFdlNzRIK000SXhQU2cKN/ebxrIWkvkFG4vhyaJa1+5wSBHMEK+h
            00up+eFE+VXE13AwkHPkatrith3P7JMYBdxTuiaePUKoNRvBFUMldQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T08:32:34Z"
    mac: ENC[AES256_GCM,data:BN8BXBPDCogfBGMEtDzW0fHgBjY46yvc3lsdSI115nomMWBq5bBi3cYSGcXG2vQBxgB5+3ssLGfjUJ6+4fznto2IBkE7V5hIJH4FhGP2EcovkXQHSiR4LeO6P0Ssu3SvppL5kpza3NZCuy9IKQRukdGnUj9CrZ6+gckADkAMvvI=,iv:3nyx3TYStOEPAGNurnh8i18zJBoz2Et8VsrxqC9IVhA=,tag:o5UjJ62GzSFxCReOhhdoJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
