windmill_postgres_password: ENC[AES256_GCM,data:x3AWasmuHxmMaYYmNUe2PRlVvVZObIWiXUVYVA==,iv:3IOeis8lZAhsFGB3oBT6QsscVI9PbDM1wz817WkOfec=,tag:XDN4ItcZHuiRwkAawYd2ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb0hWcGRpZ3BoMW9LcEpM
            aDhScXl5STVoQ1FFVTVQZEtqMmUyL3FvbFIwCkFuK01xTmNxN0dnV1VGRFVvazB2
            NFBLeWU1WElCblRvbSs4T2h2cld1azQKLS0tIEJtUjR4eWFoU0hubE9uK0E1MnVD
            Rm5DdFJDcGsrUjh2cUFpK2VnYmkyckEKvgXTJYrl92XSQS0oA1DssycvHHIjmeY+
            xBBXE+7Blo2MfhptCx3zB7qiXosM4ARVx5FOGAzr9DahxWUB8aVL5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-06T09:52:50Z"
    mac: ENC[AES256_GCM,data:lMeI9g3JgJJ2xMI1ssal0yudICcotl+Tidz1luDyxLWVb/0Z09Y+oVfiyUDxpeCHgDqDCuu3OAhnstyGcMz1afvVsyymCv3qeGcS6eB8++UJEZzr08HNMD2R6No0TJ3v06es40yLVf48nQIQN/MaxFGZwYaOoniOA7/D2m90WqE=,iv:tpN1v3Yc0paOBxiTa+szHdKLTn7z1iaZkynyYYcibCo=,tag:rgOxTfFqEJT/xUHE8R+hWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
