grimmory:
    db_password: ENC[AES256_GCM,data:pJD8A6UQ+zXeJFdyRwkHe4WdzJi/U1KAm2/APmPn1jM=,iv:/gZZogPvH5kNN7NeekCdrE6u7Zysx0kSs4hP4B6I57M=,tag:GX8lXbyMzKBKkQcgDGWZhA==,type:str]
    db_root_password: ENC[AES256_GCM,data:WKM25VdldNPyRzsMwLNgHyw2pM/y4HtmPHnIML6sQ0U=,iv:f5VLlDcaUlPAG6DIVIhbqxiQdcw+zJKa1uE8ms1zyoE=,tag:UvsgvfmaeA0gWDDD98nN8A==,type:str]
arr:
    #ENC[AES256_GCM,data:9P+b89v1RcgivUlQJ6SJlEyRPd2WZbfHpbQPXsv1bxjzTK8a//umz428z3wxwSfP3Y0t+O35hceM96BriWFbGPJid5h86vBWt82cGrbPMmo=,iv:18/Osu8St1JM7Yg1XS1KxRB89GpsBU472l72f1Kknws=,tag:Qfze+Z3DX7az/5x/p7dQsQ==,type:comment]
    sonarr_api_key: ENC[AES256_GCM,data:Ttk4t6DnLvUsVEl4wARh8D/RmNTZ0lVFB6RHlSNAG6k=,iv:XN0gzYYs0rwNhONDV8a0OkdtfbREQqJOSRN/ZJwjo5I=,tag:NQMDdUKG2717/Ld71QhYYA==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:XR+E3BQVzOryQvDAVCK8JCfndplJ76Uvs96HbFwGV6Q=,iv:RQt/R8h/fPi4jU4PwTxeDvAIH8ACkDwtqC39mb5hfdc=,tag:OiDgkEkw5fAJixf9h+MEpA==,type:str]
seedbox:
    username: ENC[AES256_GCM,data:sh4eeV5Y,iv:7VysgD2lay8/Sw9NdNUurfzVMJSXP6910GRWs3WdYjw=,tag:h2BBvgG4UClZmIeQRGVAIg==,type:str]
    qb_host: ENC[AES256_GCM,data:iDBEhApq5VFLHT8HjlKE3UbqBhnboorR90hHkbT7Pcf00LdK0I+s,iv:KVu7AQxUgLDahjg0v8/pHSDsv9xXbOi00kxAbMxI6Zw=,tag:m55rFfI+9R0bXK0duv/Pow==,type:str]
    qb_password: ENC[AES256_GCM,data:BZ6F3rqmA0Vmf2t2A7MST+aAd0o=,iv:099ouE4SUkaHnT+YwPkyjPZ9vXPq2idPcqzde22uRGg=,tag:mCyZyBBsNsCbCpR7QAhRJQ==,type:str]
    ssh_host: ENC[AES256_GCM,data:lDXF0Qtmq2+9sUXb,iv:pGJA1mTwcNJcQzJlif+RH3cf910V0kh/K+tm8K469+I=,tag:ufLdte1bFyzPS3Q0iQFRPQ==,type:str]
    ssh_password: ENC[AES256_GCM,data:c9U2nNElqH3NaJohRO1tazkpueM=,iv:iERf8iBJQB7mAIF96QYq0R3li1U4fsSnv08OZPYRKKQ=,tag:GHvIpKYpmZiBgtb8GsP3mg==,type:str]
    discord_webhook_url: ENC[AES256_GCM,data:IY8cWJWhtv2qV4YK+QQMydjUpANJtFi8epzP31mpuTNmnv41nopOvsBwS1hGhP3YOSpI+0rQvKAizQu39w/vyr3syTOGN2kPspwWaWUpLiZpYyUHvetqXIN3RdUPS2834K4lGuiojfJG5jgvGERsoWtQ2ofstPgenA==,iv:plbuLHD+zO2B72cXaeXqC2a4SuZWrGf08yl8BX6AMvc=,tag:/mLAYBNeEYyO18KLkT3Yzw==,type:str]
gluetun:
    #ENC[AES256_GCM,data:9V5EPYAmMzoZ46vxqevmWPC3OjKwzB5L,iv:BSGT4ll3HBIVqiVg2US1vFEmJSHxXj9yCI6u05M1IaE=,tag:4Q0DfDQjzq8PElty2rq98w==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:LHi0Joz5u4zgstBYzHf/kE3KttpKd4K1e85QiFh3LSpg6vA26jn3p8knVp0=,iv:TMaChgrpLlQeBUQYdP5D5LbjJJKxsE3p6hIU0yv4UQQ=,tag:rEx0os+Ub9uqPgQuNAFhuQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:cEQVARG8igR9cK5kzTkdTxDTDyr/TdR6bsnaqJcz5PI106bX9jxCZPE8kU4=,iv:N1R84cF386FUzwPrFWwvOYPcTeFT0LVP04ogUFKlNhQ=,tag:6pooao9TvKjilao/tcOH9Q==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:McUxKSPunJISPhx+NG/vaTD9rL1JoncbfOCJW5Suc7Gr/0/8q6jEBdnQ8D+sSPXLvb+bCYR2F+tl4ik=,iv:uFDrMvlaJygdEWcA9MpNHJ0rATl3aoE3ahTHR5PyqZw=,tag:f1vNuVetmj0MKtUsVg2ZnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZldackNYL2ZzTllrcHNk
            QXpvU1Q0ay8ya2NiK3VRRCtYTUI4NzlyT0NjCisrZjUyTlYweWthV2NTTGpSZUN4
            YkhsL2Q5Tm5BNUltOFRNN2lqbXpxVTAKLS0tIDdIeFAwaFlkVGFhRWEvQnlvaEtK
            VXpOVmZMaVFTYVZUWVNqNW10ak9DSmcKnyOphWN+lQtOKOJZgKN7AE36WHalfosq
            p6Mzu5MpLR4ieH0WY9/SnJ/sdzk3b/deijoWfGxUxwVSXGsUhWWNBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-04T23:37:33Z"
    mac: ENC[AES256_GCM,data:LFTkvS8YNGnOil36jJTJOrLfNfM7Zs4wqybYzLzTrJJdZqnmP8xbIXJFVTO8jxfV0GbmLgDTeoD14XC0V0L6jueQN1QfpD1lns+b1dL9Xw5doHxA8QzzLC1cC6XGr8xS9SDDyMvf5itiBjV6zMFpG3ZRwguiuT06IAQP88vm1ws=,iv:O3pVLvNQnMOHQK9V4jzt4A74nsDsrNCji+8PiDZhBFU=,tag:a/O+HgRVQG+E4oqpSs7tRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
