arr:
    #ENC[AES256_GCM,data:FElAZ1rZQIbszZLTX9WiHz0VjpIF7ZuJyKOTthfR/gKhzVAwBpb6QbF4kD4ThVxNn4aFmFmdLrWO5ttnqrNDbxMwA7VBGDWUiNNLYu3gR7A=,iv:/PZrwqpqiHK7kE7LFUbCVEH3PPYiOTdgSfb7WjVUkA0=,tag:iAxnKbvZ+8MO8Xl1C8hXOQ==,type:comment]
    sonarr_api_key: ENC[AES256_GCM,data:+lGRK+6CjANc+cR07haoPcLt+Q58TidVyB26KMAd+zY=,iv:jimX0NwmfAmRyVLVM4IHr5TegFndltG6WiV0qk6yaE8=,tag:BPapQZlqr/ETv1YrH/Djzg==,type:str]
    radarr_api_key: ENC[AES256_GCM,data:T1c2CJH6KFOzsRR8dxd7hcVOTNVtk8meCJ/0uiHPSGQ=,iv:WkjDyvXWZYtzykepGhKqNLiYTSgtUdVriQZR/mGqBbM=,tag:imtNSOLL70LqYYynmjdOcw==,type:str]
gluetun:
    #ENC[AES256_GCM,data:Z4PKJsmR0Gy9BZeRGA+3ET9WJs/lBdjf,iv:Ztv8QW02UbZ9LHzfr2i4rxkItvfab2002mqDPrOduU8=,tag:hXZ13JCIEjUjztG//mPCtA==,type:comment]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GPd0tHMmq8VaJbCslGgj+Vc0eNb+DjonHPYEv/umdSbwStYolO2Ztc875r4=,iv:xX6Xf62Ui3U/LZId0H7HslQdWYtaZu/+ZjbRFzFvfQk=,tag:DD2MGodpB4mLRnVmRn2vNQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:ltqsqN/8qchcYAQhj71lPtx13Tm3bKrHFInj05ClEf9Cjek5/Slucxyh63s=,iv:EYW70kQtkm5Cu92h8mQfxxnfmpbY3Uh5LK/Msak5oQI=,tag:6XhQFAt0EIDKfyp2B5jCvw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:darnYLYUiFS0PjnCK0mUbM8LOJgfeFqgBmmVww5hQEubkIveceD+O9DCcdXKYVzrRu8/t525Z2+eCNY=,iv:MBKw/nO4h0kdx3J6cycyz6Red49+bphxaBTScZ17pJY=,tag:WzGqdzlKJ+eZ1rrNqe3HGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0RiL25CRFVFNW8xcTFD
            Vm9FMy9UdkFuT0Jlak5ZeUlDb1A3Q3M0MUIwCmo3cnZxRVRJMXFPOEJ5NmhtT0xV
            VFVDYVJkZmdMMmF3ckk3L2llM2xPMkEKLS0tIFFLTWc5L0JVdFpoRm5PYmpXSkpK
            TENFUkx0Z21ueStzSjlvSnltNGFNNlEKpJ1CvWXeS73aciwZ8o3yt2FCgn1nSYfs
            nLM7y5Bo1umuJ7TmYAOAXLvvr/4bx1rA1X33wGpGd2ESL2N9DKiMRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-04T20:46:49Z"
    mac: ENC[AES256_GCM,data:t9AkSnBh52+Scz+5GiLHCuH6Sdr5ZrB8wmf+TI/yQG8546m3nPEyE8cJAOjR9asJkRDWeYp5n6vVuVb5RbDsAlc9BcrT4EmGSEf4wkwDUWypjJuz8xkodix491Y0PA0mwLhOC+66lbMSgWmBlMV2niKmN7iujzEr1F7i6Skophw=,iv:zXb+ubQokWzZFyr2ONdBZVIqs2u+qnBMPGtgKz/lQM0=,tag:teIculZOfeHEoK6jpeULWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
