# Disable the router-advertised DNS IPs
- import_playbook: playbook-disable-ra-dns.yaml

# Configure kube-VIP before the cluster exists
- import_playbook: playbook-kube-vip.yaml

# Install/upgrade the cluster
- import_playbook: playbook-k3s.yaml

# Fetch kubeconfig from one of the k3s nodes such that kubectl can pick it up
- import_playbook: playbook-fetch-kubeconfig.yaml

# Deploy the Tailscale exit node
- import_playbook: playbook-tailscale.yaml
