set -euo pipefail

tofu apply

header="# GENERATED BY OPENTOFU (generate_stage_data.sh) — DO NOT EDIT"

{ echo "$header"; tofu output -show-sensitive -raw ansible_yaml_inventory; } > ../20-bootstrap/inventory.yaml
{ echo "$header"; tofu output -show-sensitive -raw helmfile_values; } > ../30-applications/values.generated.yaml
