authentik:
    secret_key: ENC[AES256_GCM,data:MD/2ZtBP6mrX2Kd/8gu3fJh5O8Yi0e6BMlwXtq0oubhPb4Sb+PVL3uAM4sLnuSLcSAk=,iv:GVELOKsdzzabID2/40lz/dgE5vkhV4DxsE+hh0qQ7k0=,tag:4CtrSj7RUzn4XAF6yUfhYg==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:GST4THlwhhO+NZQuKtAiZ4kuKLWLdaOjTYQ5rjNZJyZOCZlanHGRvrjIJGT90r4GVpk=,iv:lRNneKTY89SJ49ckpFHkHQtvH7DtTZ1RJUabkV7l1ww=,tag:Lvx2YmpvAaGeu8CaxKym/A==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:WmOSGbYPmXd+Ex1hdlqx0kIsOEi1fsZ/p2VVC/23AbatvW5rdwOpWNwARVdfGJhboeI=,iv:cTpyzyEkDmbv3UHeM014M9JlyzYTv2oZmepo0X8GW40=,tag:3akbLfdP1nk0/4qKqRkI0w==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:Jk7cLVbR1CkUhhMzkirzmXZ19SRU6LEN,iv:Dg6Xfbe8EC9Hn7GBeoBM4ITNTJ3sebkttY/bTEPAtf4=,tag:Rn4X9UIz+UkdjOIvd/8T+w==,type:str]
    postgresql:
        password: ENC[AES256_GCM,data:SsVSgncDyeabeQPIokwceszJ/McgixUVDhRslw66t0PjZYH9d7SaLLCnXvHSmmKVi1s=,iv:t4i6jb4xCiIzdIBNHXMIrK49kVYQ+bUK3zBn40RD7/4=,tag:6AuI1oKle00kd9JZzIu0vQ==,type:str]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:cznEnhCjpME5X3fn3R7PIrt937e3Tilqq/czQvk8Ym5QNxVAuNmRADLsOgmXQ6hIqrc=,iv:gtfG58aUcPUZeMuzH6pi+zIO5f6EKpBjCZNrhHStVxA=,tag:S5R8Dzvnw3wbMq52SV85tw==,type:str]
#ENC[AES256_GCM,data:c5qOTAgWP4OhEJD3S8n3G0VbgFdclxshmCKDoQ==,iv:AGj45iezTmjwLKUxhgvsI1tyhU77xBNC47yj1T3DA/c=,tag:eayDvD6lYiCk9LkJhNHfzg==,type:comment]
ldap_search_password: ENC[AES256_GCM,data:WqoTDFbJ1dafCQkDFW4vKJuxy2IN2oUakU7b9dCFKMSUlUej39Hb16YJkDmr3riS4Q4=,iv:7sctH7FLEx9UjHvlfan5/yEX/SPsUTg/o6aEppGSk5U=,tag:dXc8Ph+XAXh4hWLTmEs/AQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRVMxZW80bWhicUI0MEY4
            dkI0V3ByOEZvQVR5N0swWHk3Y0pHQ2J0OXdJCnJTQnZaRVUzNjhReWUyUHhWSjJa
            L3J4RkhWZTNRRlM1WWpTamdZK1kzQUEKLS0tIEJGMkJQazZQeVRiSzJsUjlGNzNU
            MTlZSDgyTjNhVEtBeFBscU1yekRlVDQK4sZRSCl1EuGt8Sv7+rdQ15bbKAcaSC5l
            QOjpiA3dS+d+wyv+dSIW4Bz2yEJc6pQYql9YwUe1+V7byU6QJFhG8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-09-20T14:32:18Z"
    mac: ENC[AES256_GCM,data:K3blGcuntJbumMf8C07VZIYyLDyArx2z6Y3MHMqeysmTwiFe65e+rMyuVO80kDOl4Gj8XnXkZEuC3N7QYxLvJX2j0Z9EWMMQqI5yetKtzAefokSh6swTAwUtQGPUYi+R3Ejdgj45rvXO1dX76ngAyUooK85MCfCohZtvPo9xMxU=,iv:mc963JcQWekvcNGmk3Or2sKbSnuh7nwT0K+ZXiIAGzs=,tag:G7Ta+PJOibieZNLtI6Z8/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
