authentik:
    secret_key: ENC[AES256_GCM,data:jM2D97debjSvn+hADGAKmGvDulrHVnTljWHN2ywm66ESn4vi8ZIjUNW059jP6thOe/0=,iv:YdCC+BUNJjhqW+GRsy8S30rWsIyE0PJjaN8HaMRNY3U=,tag:/Ct+axiVsWjCLs4hGZT8vw==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:6//Fev8f2vk6yjRF9sEeoGhF8w7vSuyPQ9lQ42Tsgi0TBjL+r7nS8THQXPdk7NOCf6Y=,iv:IdPnaglDLamb7KahV7W9xQhSuEFyKAhZrTQ7sXRRYEg=,tag:GysSLPiUc+oU9rVgQlaNZg==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:46hldF7GsewPnVhRHrW6q9MtP3IuSRgqdZBi+fN5Q13Z5bWCpO/qFSu+iM2ETtZzrl4=,iv:cpYx5siM0mwT0AD6dzfCcrJVdpBbhlSXyCs7+JIQq4Y=,tag:DBGGmkg12hK0JKJqRTEzDQ==,type:str]
    bootstrap_email: ENC[AES256_GCM,data:efn/3e9a3hX6psOXgZyNoYWg8hL990R7,iv:JH/t9C/6vRj9pBWu8rZmBXLZRnsQC0hOv2vdUqJ5wgQ=,tag:qoJ+EJaJ6xfFfTu1Ey3FqQ==,type:str]
    email:
        from: ENC[AES256_GCM,data:lWbNP0zuPavqGlS1KbVJzopJ,iv:WagCY0nSRpQheHBjESta3rl+ob+gHh6MAJpRRvasiPE=,tag:M4O7lSGxlA26M6KpLAz0jg==,type:str]
        host: ENC[AES256_GCM,data:0cDtIIySGQO2BHMjmMX0ixI9,iv:fHJKqwlQatYgW2Bn1080nQ6JcH2TUgnaC9eJficSPuE=,tag:H23UA10B7O7w1KLON3iqiw==,type:str]
        password: ENC[AES256_GCM,data:FUUawXMthnQHh2vz19KuHw==,iv:rMe8Xni1q5NbMZWv0yFrgOb7ReYfHo6qdImZfg64ieU=,tag:JOic/EeRf3RGOoqdHA7Xdw==,type:str]
        port: ENC[AES256_GCM,data:UKn6,iv:b7t1dXsNYvpAcEaDWr5rOgA+GMnNCUfMELTiRnEaa7A=,tag:MVL97jsuGomgfDqC2XkiFQ==,type:int]
        use_ssl: ENC[AES256_GCM,data:Dz1yuiw=,iv:5aM46Dth3Zu4BrFUL/o1tPwBKrtp9B2r7s2qAMFrGww=,tag:BrQZcCXpsxK0avBVzCcCOA==,type:bool]
        use_tls: ENC[AES256_GCM,data:7jkWDg==,iv:k7oQqKJ9ZSbrzhCu+MJwp9GY+e4dpxo/0DSkoF7rK9w=,tag:nAvss7TyuOXDZgEXf3OFKQ==,type:bool]
        username: ENC[AES256_GCM,data:hwJGhkLbmsPRit3ocXOO87ec,iv:hirSR1PstbNOXYI2bC/LIIFvhWz+u5bELQfhNRfEHuQ=,tag:F9YwXevH5FETQFN73lt1Cg==,type:str]
    postgresql:
        password: ENC[AES256_GCM,data:g3qkReeNJbk09Ej2irOwNbj9zoPfMAwOGDnovAfv6Ea6MnP6FdQ9Hgv1n3zzwEKikz4=,iv:Ux0RfiSpsa3rfAZ4n6Fb5EED8Hkpsgn8RqN/UBaD+Ac=,tag:7ctyVYdB07FC0nu0Fu/8hw==,type:str]
postgresql:
    auth:
        password: ENC[AES256_GCM,data:IdKpDWBIY2wxQmROjH4Tu2gcRaQ1PEYGlyTUIUka40VpADss9KwYRcgxSKWn+/7kzn8=,iv:Cbs9ci5bjz+7WiDIOfWYExn66rm8e8QXrHipUOvMYlM=,tag:BTwOdruWy1Y82I6BGHT3sA==,type:str]
#ENC[AES256_GCM,data:sl3ZhEqWM0psN7Wldy9jFlT8xnJXXgg3hxHGRg==,iv:XyWjl6oQMb6NPbxlzMXJ1eC56SLrULflSmKnIutZAcU=,tag:C3YIFGDq1h4HC2/XipEUIQ==,type:comment]
ldap_search_password: ENC[AES256_GCM,data:PbR9qb///6hLUACJuQjPpEP3dTlebJZznjycoa809sJm/UAeUaiAGu2dZvAn6yKyQg0=,iv:pG/zroEh9wj07hFn45zUJ4w+N86sH3+9deqqoPAF05w=,tag:XrnlPwNJbviEU20Us/6O1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRmtCUEdTekwxK3VOeCtS
            QldKVVMyYW5qaGRkN0plbWhPRXVkYnQwZkN3CitIWjYzVjRZb1BZaW5tM2p4MFEx
            djRLUjJxZ0xZNnNuRnErdGNkMFNmRmsKLS0tIDdnL0N5OTBKWHJudHFraVllNDd0
            M0tOR2FpVzhKTlpUUEdtL0hhTW9kSWcKwr5/A3cvmLTtBg8egjyZAyW+xgQmQthn
            ji0YujEydZdFnktayIDTWrXgmvA9GmdF80Na6qQZVCmQlyKORg8M9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-04T16:21:13Z"
    mac: ENC[AES256_GCM,data:WUATf1GlaAkPNvR99xEciOFgHJVAUrH81EqYGudVUM4pp0oOVmmUaWos7a/pwzLs96JjCNKhU4V2VYEe7sZT0GnNwsCpigetjwbXqGyEMOYg02PIXbnH9eXhY6rXlZ+vrtpLop2vYOZCexkiAF5MI56zdP1AjPt1ycHKl+pKbPI=,iv:djU37urS0U8YvLJRixXp0ZRUvqjG50x/BsMPRiKHIjk=,tag:8DPIEOGgLn6E0Ttdf6lwUA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
