# wildcard certificates for the homelab
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-crfda
  namespace: traefik
spec:
  secretName: wildcard-crfda-tls
  dnsNames:
    - "*.{{ .Values.domain_lan }}"
    - "*.{{ .Values.domain }}"
    - "{{ .Values.domain }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
