anthropic_api_key: ENC[AES256_GCM,data:400Z5dShF/WBmCmHVPR+2EsUWh189ZJmKYDCUIdNr0Qo3CIub7FdZm198w/cvmlxZu5AzznaczGvVu4oh4B02QbR9KGcPKelqd9Um4BBHR4ZrNCh2x1eWjLGVfaq4TGc5W0AwPioQxZEaikb,iv:YGFtewR+R2IU/ybRzbZo4Gmki6qZ+cQ+wvdbT8zSJhM=,tag:B8Of3KRnnRMI3IhiuGYNuw==,type:str]
ai_postgres_password: ENC[AES256_GCM,data:JPIdZ4pdb6LKzMwTlwav63FjF7edUvWxQu6RDmrb80UYlr6TOKc32Q==,iv:yZEGHY3VB4DfruCNosIHtozrHc+AkYGKayvi00DjC+M=,tag:skGCqltflhcSk/Eh2dfDzg==,type:str]
litellm_master_key: ENC[AES256_GCM,data:EPLWz9UMNInQHXcY2yv+r3KpX5g1/PjAHI3E4L9dHBp/9k38To51HCU3CQ==,iv:E9Q+YTYAqi/IwPBRHLg54YhnNgOTHDQJ9PoEdABOXnw=,tag:H9xyH7eXElOD4TMWlaqiUw==,type:str]
claude_code_oauth_token: ENC[AES256_GCM,data:tKbWYSc/Jxj+sfiIJKcQY2/3Ouf9u7i1M7sDvY3rxEiZbuPzLKTilDY6+HmlCYAbgXhwy2MD2Px5mVOQzg/ckguA8TxbElpsC7bbupObN0eDWRxGk73BKsoc3puGxJgNETgPnMebskiIW5yp,iv:FRqZO0MIPOt6AT1vpy7SuHRj5Dpk5Lk1d7huMIMFmag=,tag:pR3oTjBMJh9VctFh9ym8hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcE84eC9nWTVTQXM4bWhF
            d0VQMmZjS3BJTTA4SVM2T044VnRHbmlWSEE0Ci9kcUZHaGVaVi9GVURaVkFHcy80
            dk5WQWNQTFZ6WGhLaGt3VEcyRXhnekkKLS0tIE02b3E2TzJ6cExxNW8rdC9hYUZy
            MzJubk5CNzdGQmpTZjZIQmsyaVZhZVkKuTQMvynjL2/nGmOTvaFsAg5nzJrYU7nC
            Ifiy3z0507X2PAduDVYJxF0SDk/snwhwjRFlfAvR+qXmIyCdXwlq0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uwg50n262c6qukmr58yvfp9jetq235m2f3r74hgyyzwd0cxs8u8s77dsvh
    lastmodified: "2026-08-20T23:25:12Z"
    mac: ENC[AES256_GCM,data:G3TPS6gpWXJydbRFvo0Rum8h4UJ8IdE8qaLH2HfbS1A1zk9j6MtqtODrJn4QdlK7t7ml37br++UtsW7PIgTH2jBChrH0GwYNNqzry9dMqUwMs8MCAKkcQUu77P6e1GzPSgNmhCozCP6+wykLilPGAR5j5LFmH36GBkz/WVswUD4=,iv:m/sfcMjrAKrC0VHmpBAvmQ6pc07K772oopnT1auBcaU=,tag:b9Ue7k9TgH28LbZPVkygKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
