apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shortener-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-zfs
  resources:
    requests:
      storage: 1Gi
